version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "npm"


