version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"


