name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          
      - name: Run unit tests
        run: go test ./...
        
      - name: Run BDD tests
        run: go test -tags=bdd -run TestBDD -timeout 60s
        
      - name: Run all tests with coverage
        run: go test -coverprofile=coverage.out ./...
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          fail_ci_if_error: false